#!/usr/bin/env bash
#
# Implexa user-hooks installer
# ──────────────────────────────────────────────────────────────────────────
# Run with:
#   curl -sL https://raw.githubusercontent.com/Implexa-Inc/implexa-claude-plugin/main/scripts/install-user-hooks.sh | bash
#
# What it does (one-time setup, idempotent — safe to re-run):
#   1. Verifies jq is installed (installs via Homebrew if missing)
#   2. Reads IMPLEXA_API_KEY from env or prompts you for one
#   3. Writes ~/.claude/implexa-hook.sh   — launcher script with PATH fix
#   4. Writes ~/.claude/implexa.env       — config file (chmod 600)
#   5. Patches ~/.claude/settings.json    — registers user-level hooks
#   6. Runs a smoke test to verify the chain works
#   7. Backs up your previous settings.json
#
# Why user-level hooks (not just plugin hooks)?
#   Claude Desktop / Cowork sandbox plugin-packaged hooks/hooks.json (the
#   --setting-sources user flag). To make UserPromptSubmit + Stop +
#   PostToolUse fire on every surface, the hooks must be at the user level
#   in ~/.claude/settings.json. This script installs them there.
#
# After this script: fully quit Claude (Cmd+Q on Mac) and relaunch.

set -e

CLAUDE_DIR="$HOME/.claude"
LAUNCHER="$CLAUDE_DIR/implexa-hook.sh"
CONFIG="$CLAUDE_DIR/implexa.env"
SETTINGS="$CLAUDE_DIR/settings.json"
BACKUP="$SETTINGS.implexa-backup-$(date +%s)"

# Color helpers — readable on most terminals
if [ -t 1 ]; then
  C_GREEN='\033[0;32m'; C_RED='\033[0;31m'; C_YELLOW='\033[0;33m'; C_BLUE='\033[0;34m'; C_BOLD='\033[1m'; C_RESET='\033[0m'
else
  C_GREEN=''; C_RED=''; C_YELLOW=''; C_BLUE=''; C_BOLD=''; C_RESET=''
fi

ok()   { printf "${C_GREEN}✓${C_RESET} %s\n"  "$*"; }
warn() { printf "${C_YELLOW}⚠${C_RESET} %s\n" "$*"; }
err()  { printf "${C_RED}✗${C_RESET} %s\n"    "$*" >&2; }
info() { printf "${C_BLUE}→${C_RESET} %s\n"   "$*"; }

echo ""
echo "${C_BOLD}🔧 Implexa user-hooks installer${C_RESET}"
echo ""

# ─── 1. Sanity check: ~/.claude exists ─────────────────────────────────
if [ ! -d "$CLAUDE_DIR" ]; then
  err "$CLAUDE_DIR not found. Install Claude Code first:"
  echo "    https://docs.anthropic.com/claude/docs/claude-code"
  exit 1
fi
ok "Claude config directory found at $CLAUDE_DIR"

# ─── 2. Check jq ────────────────────────────────────────────────────────
if ! command -v jq >/dev/null 2>&1; then
  warn "jq is required but not installed."
  if command -v brew >/dev/null 2>&1; then
    info "Installing jq via Homebrew..."
    brew install jq
    ok "jq installed"
  else
    err "Homebrew not found. Install jq manually:"
    echo "    https://github.com/jqlang/jq"
    echo "  Or install Homebrew first: https://brew.sh"
    exit 1
  fi
else
  ok "jq found at $(command -v jq)"
fi

# ─── 3. Check Python (for settings.json patching) ──────────────────────
if ! command -v python3 >/dev/null 2>&1; then
  err "python3 required but not found. Install Python 3:"
  echo "    https://www.python.org/downloads/"
  exit 1
fi
ok "python3 found"

# ─── 4. Get the API key (env or prompt) ────────────────────────────────
API_KEY="${IMPLEXA_API_KEY:-}"
if [ -z "$API_KEY" ]; then
  echo ""
  echo "${C_BOLD}Enter your Implexa API key (imp_live_...):${C_RESET}"
  echo "Get one at https://app.implexa.ai/install"
  echo -n "API key: "
  read -r API_KEY
  echo ""
  if [ -z "$API_KEY" ]; then
    err "No API key provided. Aborting."
    exit 1
  fi
fi
case "$API_KEY" in
  imp_*) ok "API key looks valid (starts with imp_)" ;;
  *)     warn "API key doesn't start with 'imp_' — proceeding anyway, but double-check it's correct" ;;
esac

# ─── 5. Backup existing settings.json ──────────────────────────────────
if [ -f "$SETTINGS" ]; then
  cp "$SETTINGS" "$BACKUP"
  ok "Backed up $SETTINGS → $BACKUP"
else
  echo '{}' > "$SETTINGS"
  ok "Created empty $SETTINGS"
fi

# ─── 6. Write config file (with restrictive permissions) ───────────────
cat > "$CONFIG" << EOF
# Implexa hook config — auto-generated by install-user-hooks.sh
# This file is sourced by ~/.claude/implexa-hook.sh so the hook script
# has access to your API key even when Claude is launched from Finder
# (where shell env vars from ~/.zshrc are NOT inherited).
export IMPLEXA_API_KEY="$API_KEY"
export IMPLEXA_API_URL="https://core.implexa.ai"
EOF
chmod 600 "$CONFIG"
ok "Wrote config: $CONFIG (chmod 600 — only you can read it)"

# ─── 7. Write launcher script ──────────────────────────────────────────
cat > "$LAUNCHER" << 'EOF'
#!/usr/bin/env bash
# Implexa hook launcher.
#
# Stable entry point referenced from ~/.claude/settings.json. Resolves the
# currently-installed plugin version dynamically so it survives plugin
# updates. Sources implexa.env so env vars are available even when Claude
# is launched from Finder (GUI env vs shell env).

# Add Homebrew bin paths — Claude Desktop's GUI process has a minimal PATH.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

# Source the config file if shell env didn't provide IMPLEXA_API_KEY.
if [ -z "${IMPLEXA_API_KEY:-}" ] && [ -f "$HOME/.claude/implexa.env" ]; then
  set -a
  source "$HOME/.claude/implexa.env"
  set +a
fi

# Find the currently-installed plugin's hook script.
PLUGIN_DIR=$(ls -td "$HOME/.claude/plugins/cache/implexa/implexa/"*/ 2>/dev/null | head -n 1)
if [ -z "$PLUGIN_DIR" ]; then exit 0; fi

# Forward the stdin payload + event to the plugin's hook handler.
exec "$PLUGIN_DIR/hooks/implexa-event.sh"
EOF
chmod +x "$LAUNCHER"
ok "Wrote launcher: $LAUNCHER"

# ─── 8. Patch settings.json (idempotent) ───────────────────────────────
python3 << PYEOF
import json, os, sys
p = os.path.expanduser('$SETTINGS')
with open(p) as f:
    s = json.load(f)
s.setdefault('hooks', {})
LAUNCHER_CMD = '\$HOME/.claude/implexa-hook.sh'
added = []
already = []
for event in ['UserPromptSubmit', 'Stop', 'PostToolUse']:
    s['hooks'].setdefault(event, [])
    # Find or create the matcher='*' group
    target = None
    for matcher_group in s['hooks'][event]:
        if matcher_group.get('matcher') in ('*', ''):
            target = matcher_group
            break
    if target is None:
        target = {'matcher': '*', 'hooks': []}
        s['hooks'][event].append(target)
    target.setdefault('hooks', [])
    # Add our hook if not already there
    if not any(h.get('command') == LAUNCHER_CMD for h in target['hooks']):
        target['hooks'].append({'type': 'command', 'command': LAUNCHER_CMD})
        added.append(event)
    else:
        already.append(event)
with open(p, 'w') as f:
    json.dump(s, f, indent=2)
if added:
    print('Registered hooks for: ' + ', '.join(added))
if already:
    print('Already registered for: ' + ', '.join(already))
PYEOF
ok "settings.json patched"

# ─── 9. Smoke test ─────────────────────────────────────────────────────
echo ""
info "Running smoke test (simulates Claude Desktop's clean GUI environment)..."
SMOKE_PAYLOAD='{"hook_event_name":"UserPromptSubmit","prompt":"installer smoke test","session_id":"installer","transcript_path":"/tmp/nope","cwd":"/tmp"}'
if env -i HOME="$HOME" PATH="/usr/bin:/bin" \
     bash -c "echo '$SMOKE_PAYLOAD' | '$LAUNCHER'" >/dev/null 2>&1; then
  ok "Smoke test passed — launcher runs cleanly in GUI-like environment"
else
  err "Smoke test failed."
  echo "Diagnostic info:"
  echo "  - jq location:        $(command -v jq || echo 'NOT FOUND')"
  echo "  - launcher exists:    $([ -x "$LAUNCHER" ] && echo 'yes' || echo 'NO')"
  echo "  - plugin installed:   $(ls -d "$HOME/.claude/plugins/cache/implexa/implexa/"*/ 2>/dev/null | head -1 || echo 'NO')"
  echo "  - config exists:      $([ -r "$CONFIG" ] && echo 'yes' || echo 'NO')"
  echo ""
  echo "If the plugin isn't installed yet, install it first:"
  echo "  /plugin marketplace add https://github.com/Implexa-Inc/implexa-claude-plugin.git"
  echo "  /plugin install implexa@implexa"
  exit 1
fi

# ─── 10. Done ───────────────────────────────────────────────────────────
echo ""
echo "${C_BOLD}${C_GREEN}🎉 Setup complete.${C_RESET}"
echo ""
echo "${C_BOLD}Next steps:${C_RESET}"
echo "  1. ${C_BOLD}Fully quit Claude${C_RESET} (Cmd+Q on Mac — not just close the window)"
echo "  2. Relaunch Claude"
echo "  3. Run ${C_BOLD}/implexa:record-skill${C_RESET} to test capture"
echo ""
echo "Verify the capture worked: visit app.implexa.ai/skills/<your-skill-slug>/raw-capture"
echo "If conversationTurns > 0, hooks are firing — the killer feature is live."
echo ""
echo "Settings backup saved at: $BACKUP"
echo "(In case you ever need to restore: cp $BACKUP $SETTINGS)"
echo ""
